### ISSUE TITLE
Audio / sound drivers kext

### ISSUE THREAD

**Issue by wilber82** [img2tab/macos-guest-virtualbox#47]
This maybe not the script issue. Do you guys able to enable sound card after installation?

**Comment by img2tab** [comment]
Enabling audio/sound is outside the scope of this script.

After installation, you can try installing open-source audio drivers from [VoodooHDA](https://github.com/chris1111/VoodooHDA-2.9.0-Clover-V12/releases/tag/V12).

**Comment by img2tab** [comment]
Enabling audio/sound is outside the scope of this script.

After installation, you can try installing open-source audio drivers from [VoodooHDA](https://github.com/chris1111/VoodooHDA-2.9.0-Clover-V12/releases/tag/V12). This currently doesn't work since the drivers don't support any of the VirtualBox audio devices.

If you REALLY need this, you can either code new audio devices for VirtualBox or code support for the existing VBox audio devices for VoodooHDA.
