### ISSUE TITLE
Stopped at EFI shell prompt after detaching initial base system

### ISSUE THREAD

**Issue by Xamelok** [img2tab/macos-guest-virtualbox#51]
Hello

Windows 7 SP1 x64 host
VirtualBox 5.2.28

install script original - latest version.

At this step 
![Cygwin](https://user-images.githubusercontent.com/50046912/56849065-7ecc3100-68f8-11e9-889b-ca6ba298ba5d.jpg)

after guest shut down and then boot again a have this screen:
![VirtualBox_Mojave_27_04_2019_14_17_27](https://user-images.githubusercontent.com/50046912/56849062-6fe57e80-68f8-11e9-991b-f7adfb82c932.png)

What should i do next.

**Comment by img2tab** [comment]
Most likely the download failed or the `asr` command failed to execute. This is because the script is not robust and fails due to errant keystrokes. 
You can either restart the script entirely, or continue from the `boot_macos_installer` step after re-attaching the initial base system and manually executing the failed commands.
Please report if this solves the issue.

**Comment by img2tab** [comment]
Closing until further details are available.

**Comment by ncgreco1440** [comment]
I don't have much to say other than when I got the same error, I redid the entire process but the second time I opt to not remove the temporary files and I made my decision quickly rather than wait for the EFI shell prompt to sit around. 

It *just worked* when I took those steps. 

VM VirtualBox v6.0 with AppleSupport 2.0.4
