### ISSUE TITLE
Get into UEFI shell after completed installation

### ISSUE THREAD

**Issue by ksmolyanin** [img2tab/macos-guest-virtualbox#71]
Script completed without errors and says: "That's it. Enjoy your virtual machine."

But I get into UEFI shell instead of macOS. There are some files that can't be found.

![screenshot_1](https://user-images.githubusercontent.com/944028/59673199-8659d900-91c9-11e9-8927-7069da2755ca.png)

VirtualBox 5.2.18 (on Linux Mint)

**Comment by img2tab** [comment]
The script appears to have misplaced the files from [AppleSupport-v2.0.4-RELEASE.zip](https://github.com/acidanthera/AppleSupportPkg/releases/tag/2.0.4). Without them, VirtualBox can't boot from APFS partitions. Please attach the virtual disk image to your favorite Linux distro and mount the EFI partition then extract all the `.efi` files from the archive into `/path/to/efi/partition/`**`driver/`**

Alternatively, restart the installation and make sure every step executes properly, as the script is prone to breaking due to errant keystrokes.

**Comment by ksmolyanin** [comment]
Thank you! I've more carefully applied script instructions and everything was ok.
